<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>NAI-MOUNTAIN-BRAIN-TRADER-V5-1</AssemblyName>
    <RootNamespace>cAlgo.Robots</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="cTrader.Automate" Version="1.*-*" />
  </ItemGroup>
</Project>
