const GROQ_URL='https://api.groq.com/openai/v1/chat/completions';
const GEMINI_BASE='https://generativelanguage.googleapis.com/v1beta/models';

const SCHOOL=`NAI TRADING SCHOOL, compact runtime edition:
1. Watch, understand, judge, trade, manage and journal. WAIT is valid; trading is not mandatory.
2. Price is an ordered path, not isolated ticks. Judge where it travelled, how directly, and how much it retraced.
3. Noise is ordinary back-and-forth that does not meaningfully change the larger journey. Judge noise relative to recent volatility.
4. Main move means the directional journey that matters for the intended holding horizon. It is not a fixed tick count.
5. Trend is horizon-relative. A short horizon can disagree with a longer horizon.
6. UP and DOWN moves may contain pullbacks. A counter-leg is not automatically a reversal.
7. Chop means repeated back-and-forth with poor net progress. Prefer WAIT when no directional edge exists.
8. An impulse is a strong directional push. It can justify an early attack when direction looks good, but strong direction can also become extended.
9. Structure is the sequence of meaningful swings: higher highs / higher lows often support UP; lower lows / lower highs often support DOWN.
10. A protected swing is a structural level that should survive if the current thesis is right.
11. Pullback = movement against an established move without invalidating it. Resumption = movement returning with the main direction after pullback.
12. Do NOT require pullback/resumption before every entry. In DEMO, a fresh strong directional move may be attacked immediately when you judge the edge is good. Learn from losses.
13. Fake breakout/resumption fails quickly. Failure to follow through is information.
14. Extension and exhaustion matter. Correct direction at poor location can still be a bad trade.
15. Transition is uncertainty between established states. Reversal requires meaningful structural damage plus new opposite progress.
16. Every BUY/SELL needs a concise thesis and invalidation. BUY is never required just because market is UP; SELL is never required just because recent ticks are DOWN.
17. HOLD means the original thesis still has enough support. EXIT when thesis deteriorates, structure invalidates, target/risk is reached, or continuation weakens enough.
18. Risk laws are external and cannot be rewritten. Profit target is a mission, not permission to force trades.
19. Never use future information. Judge only the live packet available now.
20. Be decisive but not theatrical. Return concise auditable judgment, not hidden chain-of-thought.`;

const OUTPUT=`Return exactly one compact JSON object:
{"action":"BUY|SELL|WAIT|HOLD|EXIT","main_move":"UP|DOWN|NONE|TRANSITION","phase":"IMPULSE|TREND_ESTABLISHED|PULLBACK|RESUMING|EXTENDED|BREAKING|CHOP|TRANSITION|UNKNOWN","horizon":"5-20s|20-60s|1-3m|MIXED","confidence":0-100,"location":"GOOD|ACCEPTABLE|POOR|UNKNOWN","thesis":"short","evidence":["short","short"],"invalidation":"short","urgency":"NOW|SOON|NONE"}`;

function extract(raw){if(raw&&typeof raw==='object')return raw;const t=String(raw||'').trim();try{return JSON.parse(t)}catch{}const m=t.match(/\{[\s\S]*\}/);if(m){try{return JSON.parse(m[0])}catch{}}return null}
function normalize(j={}){const action=['BUY','SELL','WAIT','HOLD','EXIT'].includes(j.action)?j.action:'WAIT';const move=['UP','DOWN','NONE','TRANSITION'].includes(j.main_move)?j.main_move:'NONE';const phase=['IMPULSE','TREND_ESTABLISHED','PULLBACK','RESUMING','EXTENDED','BREAKING','CHOP','TRANSITION','UNKNOWN'].includes(j.phase)?j.phase:'UNKNOWN';const horizon=['5-20s','20-60s','1-3m','MIXED'].includes(j.horizon)?j.horizon:'MIXED';const location=['GOOD','ACCEPTABLE','POOR','UNKNOWN'].includes(j.location)?j.location:'UNKNOWN';const urgency=['NOW','SOON','NONE'].includes(j.urgency)?j.urgency:'NONE';return{action,main_move:move,phase,horizon,confidence:Math.max(0,Math.min(100,Number(j.confidence)||0)),location,thesis:String(j.thesis||'No clear thesis.').slice(0,220),evidence:(Array.isArray(j.evidence)?j.evidence:[]).slice(0,3).map(x=>String(x).slice(0,150)),invalidation:String(j.invalidation||'Unknown').slice(0,160),urgency}}
function packet(body){const e=body?.eyes||{};return{mode:body?.mode||'demo',trader:body?.trader,market:body?.market||'Volatility 25 (1s)',now:body?.now||Date.now(),position:body?.position?{side:body.position.side,liveProfit:body.position.liveProfit,peakProfit:body.position.peakProfit,trailFloor:body.position.trailFloor,boughtAt:body.position.boughtAt,context:String(body.position.context||'').slice(0,180)}:null,eyes:{last_price:e.last_price,median_step:e.median_step,horizons:e.horizons,filmstrip_5s:e.filmstrip_5s,filmstrip_10s:e.filmstrip_10s,filmstrip_30s:e.filmstrip_30s,candidate_swings:e.candidate_swings,recent_prices:e.recent_prices},recent:(Array.isArray(body?.recent)?body.recent:[]).slice(-2).map(x=>({action:x.action,main_move:x.main_move,phase:x.phase,confidence:x.confidence}))}}
async function groq(key,model,payload){const r=await fetch(GROQ_URL,{method:'POST',headers:{Authorization:`Bearer ${key}`,'content-type':'application/json'},body:JSON.stringify({model,temperature:.15,max_completion_tokens:260,response_format:{type:'json_object'},messages:[{role:'system',content:`You are GROQ TRADER inside NAI (Naimah AI). You trade independently.\n${SCHOOL}\n${OUTPUT}`},{role:'user',content:`LIVE NAI EYES PACKET:\n${JSON.stringify(payload)}`} ]})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(j?.error?.message||`Groq ${r.status}`),{status:r.status,retryAfter:Number(r.headers.get('retry-after')||0)});const out=extract(j?.choices?.[0]?.message?.content);if(!out)throw Object.assign(new Error('Groq returned unreadable JSON.'),{status:502});return{judgment:normalize(out),model:j?.model||model,usage:j?.usage||null}}
async function gemini(key,model,payload){const url=`${GEMINI_BASE}/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`;const prompt=`You are GEMINI TRADER inside NAI (Naimah AI). You trade independently.\n${SCHOOL}\n${OUTPUT}\nLIVE NAI EYES PACKET:\n${JSON.stringify(payload)}`;const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{temperature:.15,maxOutputTokens:280,responseMimeType:'application/json'}})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(j?.error?.message||`Gemini ${r.status}`),{status:r.status});const raw=j?.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'';const out=extract(raw);if(!out)throw Object.assign(new Error('Gemini returned unreadable JSON.'),{status:502});return{judgment:normalize(out),model,usage:j?.usageMetadata||null}}

export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'POST only'});const body=req.body||{};const trader=String(body.trader||'').toUpperCase();if(!['GROQ','GEMINI'].includes(trader))return res.status(400).json({error:'trader must be GROQ or GEMINI'});if(!body.eyes)return res.status(400).json({error:'NAI Eyes packet is required.'});try{const payload=packet(body);if(trader==='GROQ'){const key=String(req.headers?.['x-nai-groq-key']||'').trim()||process.env.GROQ_API_KEY;if(!key)return res.status(503).json({error:'Groq API key missing.'});const result=await groq(key,body.model||'qwen/qwen3.8-27b',payload);return res.status(200).json({trader,...result})}const key=String(req.headers?.['x-nai-gemini-key']||'').trim()||process.env.GEMINI_API_KEY;if(!key)return res.status(503).json({error:'Gemini API key missing.'});const result=await gemini(key,body.model||'gemini-2.5-flash',payload);return res.status(200).json({trader,...result})}catch(e){return res.status(e.status||500).json({error:e.message||'NAI AI request failed.',retryAfter:e.retryAfter||null})}}
